### ISSUE TITLE
Enhanced key selection in TLS 1.3 based on client signature algorithms

### ISSUE THREAD

**Issue by ryru** [ryru/strongswan#16]
The code that follows in this block probably isn't a good fit for the TLS 1.3 case. Instead we should perhaps use the values in the signature algorithms extension as indicator whether we can use the key we found initially and perhaps switch to a different one if available (there are also additional key types besides RSA and ECDSA, so instead of a simple switch we should derive the key types from the supported signature schemes and them look for a key using that).

_Originally posted by @tobiasbrunner in https://github.com/ryru/strongswan/pull/12#discussion_r490147061_

Test with:
```
openssl s_client -sigalgs ECDSA+SHA512 -connect localhost:8443 -debug -keylogfile tls13-secrets.keys
```
or use `RSA+SHA256` etc.

**Comment by tobiasbrunner** [comment]
Note that [RFC 8422](https://tools.ietf.org/html/rfc8422) also defines the use of EdDSA keys for older TLS versions via _signature_algorithms_ extension.
